### ISSUE TITLE
Doesn't work in FF

### ISSUE THREAD

**Issue by heubergen** [ExE-Boss/new-tab-image#1]
I just downloaded your Extensions and tried it on this page (http://www.watson.ch/Digital/So%20%C3%BCberwacht%20uns%20der%20Staat/306354110-Drastische-Massnahme-wegen-Terror-Angst--Vor-dem-CL-Finale-wird-jedes-Gesicht-gescannt) but it seems not to work as expected.
I can't see any new entry in the contect menu:
![screen-000159](https://cloud.githubusercontent.com/assets/5529410/25473425/b98282da-2b2f-11e7-9ec3-47c9d1edf86d.png)

**Comment by ExE-Boss** [comment]
That's because it's currently added through the [&lt;menu&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu) element, instead of the WebExtensions [contextMenus](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus) API. And if the image already has it's own custom context menu, then I can't add my own menu item to it.

Also, it works for me:
![view image in new tab](https://cloud.githubusercontent.com/assets/3889017/25487215/d51dce80-2b63-11e7-9c53-fa3e8680f1ff.png)

**Comment by heubergen** [comment]
I understand now why I ran into this issue:
I installed your extension from AMO (https://addons.mozilla.org/en-US/firefox/addon/new-tab-image_exe-boss/).
When I try your build from github for my platform it seems to work.

Could I look into the API and send you a PR or are you on it?

**Comment by ExE-Boss** [comment]
That's odd, I installed it from AMO too, and it works fine for me.

Anyway, I'm looking into the WebExtensions [contextMenus](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus) API and I probably will change the implementation to use it.

**Comment by heubergen** [comment]
I just installed the extensions via sideloading and it seems to work really good, thank you for your very fast responds :)
